<?php

namespace Database\Factories;

use App\Models\AiPrompt;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\AiPrompt>
 */
class AiPromptFactory extends Factory
{
    protected $model = AiPrompt::class;

    public function definition(): array
    {
        return [
            'version_name' => 'v1.0-' . $this->faker->unique()->numberBetween(100, 999),
            'system_prompt' => 'Anda adalah penyusun pesan keadaan darurat untuk ResponSetara. Output wajib JSON.',
            'is_active' => false,
            'notes' => 'Generated by factory',
        ];
    }
}
